In [4]:
import torch
import torch.distributions as dist

In [13]:
## Let's create a Bernoulli distribution

bernoulli = dist.Bernoulli(probs=torch.tensor([0.5]))
print(bernoulli)

## Sample from the distribution
for _ in range(10):
    print(bernoulli.sample())

Bernoulli(probs: tensor([0.5000]))
tensor([1.])
tensor([0.])
tensor([0.])
tensor([0.])
tensor([1.])
tensor([1.])
tensor([0.])
tensor([1.])
tensor([0.])
tensor([0.])


In [24]:
samples = [bernoulli.sample() for _ in range(1000)]
print(f"Mean: {torch.stack(samples).mean()}")
print(f"Variance: {torch.stack(samples).var()}")

Mean: 0.5040000081062317
Variance: 0.2502342462539673


In [26]:
## lets create a normal distribution
normal = dist.Normal(loc=torch.tensor(0.0), scale=torch.tensor(1.0))
for _ in range(10):
    print(normal.sample())


tensor(-0.2342)
tensor(0.8917)
tensor(0.7596)
tensor(0.1189)
tensor(-1.0408)
tensor(-1.7291)
tensor(0.6129)
tensor(-1.2654)
tensor(-0.2360)
tensor(-0.7319)


In [27]:
samples = [normal.sample() for _ in range(1000)]
print(f"Mean: {torch.stack(samples).mean()}")
print(f"Variance: {torch.stack(samples).var()}")

Mean: 0.030698565766215324
Variance: 0.9845752716064453
